# Generated by Django 4.1.6 on 2023-02-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='descripcion',
            field=models.CharField(max_length=400),
        ),
    ]
