# Generated by Django 4.1.6 on 2023-02-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_alter_restaurant_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
